### ISSUE TITLE
"%date:MM%"(month) prefix is 'hour' instead.

### ISSUE THREAD

**Issue by dzfl** [nkchocoai/ComfyUI-SaveImageWithMetaData#13]
https://github.com/nkchocoai/ComfyUI-SaveImageWithMetaData/blob/72e40f09504d738e9f49d22a2320932053e6e881/py/nodes/node.py#L182

It seems that 'hour' is used instead of 'month' where it should be.
Could you please make the correction? thx,

**Comment by nkchocoai** [comment]
Sorry for the delay in noticing.
Thank you for your report.
