### ISSUE TITLE
Bug in nodes.py Line 182

### ISSUE THREAD

**Issue by ckmwai** [nkchocoai/ComfyUI-SaveImageWithMetaData#14]
Hi,
I found a small bug that is still existing as well as in your latest branch.

Location node/node.py Line 182

`date_table = {
                    "yyyy": now.year,
                    "MM": now.hour,
                    "dd": now.day,
                    "hh": now.hour,
                    "mm": now.minute,
                    "ss": now.second,
                }`

MM need to be

`"MM": now.month`

Best regards

**Comment by nkchocoai** [comment]
Sorry for the delay in noticing.
Thank you for your report.

**Comment by ckmwai** [comment]
No worries! You're welcome
