### ISSUE TITLE
How do I change the path to save the file in?

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [nkchocoai/ComfyUI-SaveImageWithMetaData#16]
I would like to have a `%date:yyyy-MM-dd%` path so that all images from one day are automatically placed in a folder.

Can I change this with the name prefix? I couldn't find any information in the documentation and I couldn't figure out a format that works.

**Comment by nkchocoai** [comment]
Separate filename_prefix with “/” will save the images in that folder.
`%date:yyyy-MM-dd%/Image`
![image](https://github.com/nkchocoai/ComfyUI-SaveImageWithMetaData/assets/156806390/a71abaf3-b3bf-4819-9228-866aeb93b4fc)

**Comment by MNeMoNiCuZ** [comment]
Perfect! Thank  you.
If anyone is looking for how to add the date to this, the format is:

Filename:
`%date:yyyy-MM-dd%/%date:yyyy-MM-dd - hh.mm.ss%`
Outputs: 
`2024-06-02 - 20.20.06`
