### ISSUE TITLE
Option to not add _00001_ to file names?

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [nkchocoai/ComfyUI-SaveImageWithMetaData#17]
It would be great with an option to not add a "_00001_" to the end of a file name. 

I understand that sometimes you may save multiple files with the same name.

In that case we should add numbers. 

But if it's not needed because the user already has a unique input name, can we please avoid adding the `_00001_` to the filename?

**Comment by nkchocoai** [comment]
Added option “add_counter_to_filename” to switch between adding “_00001_” or not.

**Comment by MNeMoNiCuZ** [comment]
Brilliant! Confirmed working. Thank you very much <3
