### ISSUE TITLE
Getting Lora info from Lora Stacker nodes (or multiple Lora loader nodes)

### ISSUE THREAD

**Issue by Vik71it** [nkchocoai/ComfyUI-SaveImageWithMetaData#25]
Since I often use multiple Loras, it would be useful to be able to get the Lora data associated to the image, for Civitai, also from the various Lora Stack nodes (or, for example, from multiple Lora Loader, like "Power Lora Loader (rgthree)"). Otherwise, when Lora are present, I need to change the links to the Load Lora Tag each time I change the number of Loras

**Comment by simon-kyger** [comment]
upvoting this.  i may make a fork and try my hand to implement this if i have time.

**Comment by nkchocoai** [comment]
Supported [efficiency-nodes](https://github.com/jags111/efficiency-nodes-comfyui) and [rgthree](https://github.com/rgthree/rgthree-comfy)'s LoRA Stacker.

**Comment by Vik71it** [comment]
Thanks a lot for this feature !
